import React, { useState, useRef, useEffect } from "react";
import { Link, useNavigate, useLocation } from "react-router-dom";
import AuthCard from "../components/AuthCard";
import { verifyOtp, forgotPassword } from "../patient/services/authService";
import { useTranslation } from "react-i18next";
import "./Auth.css";

const OtpVerification = () => {
    const navigate = useNavigate();
    const location = useLocation();
    const { t } = useTranslation();
    const email = location.state?.email || "";

    const [otp, setOtp] = useState(["", "", "", "", "", ""]);
    const [loading, setLoading] = useState(false);
    const [resendLoading, setResendLoading] = useState(false);
    const [error, setError] = useState("");
    const [successMsg, setSuccessMsg] = useState("");
    const inputsRef = useRef([]);

    useEffect(() => {
        if (!email) {
            navigate("/forgot-password");
        }
    }, [email, navigate]);

    const handleOtpChange = (index, value) => {
        // Only allow numbers
        if (!/^\d*$/.test(value)) return;

        const newOtp = [...otp];
        // Take only the last character if they pasted or typed multiple
        newOtp[index] = value.slice(-1);
        setOtp(newOtp);

        // Move to next input
        if (value && index < 5) {
            inputsRef.current[index + 1].focus();
        }
    };

    const handleKeyDown = (index, e) => {
        if (e.key === "Backspace" && !otp[index] && index > 0) {
            inputsRef.current[index - 1].focus();
        }
    };

    const handlePaste = (e) => {
        e.preventDefault();
        const pastedData = e.clipboardData.getData("text").slice(0, 6).replace(/\D/g, "");
        if (pastedData) {
            const newOtp = [...otp];
            for (let i = 0; i < pastedData.length; i++) {
                newOtp[i] = pastedData[i];
            }
            setOtp(newOtp);
            // Focus the next empty input or the last one
            const nextIndex = Math.min(pastedData.length, 5);
            inputsRef.current[nextIndex].focus();
        }
    };

    const handleResend = async () => {
        setResendLoading(true);
        setError("");
        setSuccessMsg("");
        try {
            await forgotPassword(email);
            setSuccessMsg("OTP has been resent to your email.");
        } catch (err) {
            let errorMessage = "Failed to resend OTP. Please try again.";
            if (err.response?.data?.errors) {
                const errors = err.response.data.errors;
                const firstKey = Object.keys(errors)[0];
                if (firstKey && errors[firstKey].length > 0) {
                    errorMessage = errors[firstKey][0];
                }
            } else if (err.response?.data?.message) {
                errorMessage = err.response.data.message;
            } else if (typeof err.response?.data === 'string' && err.response.data.trim() !== '') {
                errorMessage = err.response.data;
            }
            setError(errorMessage);
        } finally {
            setResendLoading(false);
        }
    };

    const handleSubmit = async (e) => {
        e.preventDefault();
        const otpValue = otp.join("");
        if (otpValue.length < 6) {
            setError("Please enter all 6 digits.");
            return;
        }

        setLoading(true);
        setError("");
        setSuccessMsg("");

        try {
            const responseData = await verifyOtp(email, otpValue);
            
            // Extract the actual reset token generated by ASP.NET Identity from the response
            const token = typeof responseData === 'string' 
                ? responseData 
                : (responseData?.token || responseData?.resetToken || responseData?.data || otpValue);

            navigate("/reset-password", { state: { email, resetToken: token } });
        } catch (err) {
            let errorMessage = "Invalid OTP. Please try again.";
            if (err.response?.data?.errors) {
                const errors = err.response.data.errors;
                const firstKey = Object.keys(errors)[0];
                if (firstKey && errors[firstKey].length > 0) {
                    errorMessage = errors[firstKey][0];
                }
            } else if (err.response?.data?.message) {
                errorMessage = err.response.data.message;
            } else if (typeof err.response?.data === 'string' && err.response.data.trim() !== '') {
                errorMessage = err.response.data;
            }
            setError(errorMessage);
        } finally {
            setLoading(false);
        }
    };

    const obscureEmail = (em) => {
        if (!em) return "";
        const [name, domain] = em.split("@");
        if (name.length > 2) {
            return `${name.substring(0, 2)}${"*".repeat(name.length - 2)}@${domain}`;
        }
        return em;
    };

    return (
        <AuthCard
            title={t("auth.enter_otp")}
            subtitle={`${t("auth.otp_subtitle")}${obscureEmail(email)}`}
            icon="fa-solid fa-shield-halved"
        >
            <form onSubmit={handleSubmit}>
                <div className="otp-container mt-2" onPaste={handlePaste}>
                    {[0, 1, 2, 3, 4, 5].map((index) => (
                        <input
                            key={index}
                            type="text"
                            maxLength="1"
                            className="otp-input"
                            required
                            value={otp[index]}
                            ref={(el) => (inputsRef.current[index] = el)}
                            onChange={(e) => handleOtpChange(index, e.target.value)}
                            onKeyDown={(e) => handleKeyDown(index, e)}
                        />
                    ))}
                </div>

                {error && <div className="auth-error-message mt-3" style={{ color: 'red', textAlign: 'center' }}>{error}</div>}
                {successMsg && <div className="auth-success-message mt-3" style={{ color: 'green', textAlign: 'center' }}>{successMsg}</div>}

                <button type="submit" className="auth-submit-btn mt-4" disabled={loading}>
                    {loading ? t("auth.verifying") : t("auth.verify_code")}
                </button>

                <div className="text-center mt-4">
                    <button
                        type="button"
                        className="auth-link small-text text-muted"
                        style={{ background: 'none', border: 'none', padding: 0, cursor: 'pointer' }}
                        onClick={handleResend}
                        disabled={resendLoading}
                    >
                        {resendLoading ? t("auth.resending") : t("auth.resend_btn")}
                    </button>
                </div>
            </form>
        </AuthCard>
    );
};

export default OtpVerification;
